### PR TITLE
Set the debugger to Xamarin to save user headaches

### PR DESCRIPTION
**Pull request by ggailey777**
This caused me so much of a headache....we probably should also set this in the master branch too.

### CODE REVIEW

**Comment by azurecla** [comment]
Hi **@ggailey777**, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <p>
        It looks like you're working at Microsoft (glenga). If you're full-time, we DON'T require a contribution license agreement.
    </p>
    <p>
        If you are a vendor, DO please sign the electronic contribution license agreement. It will take 2 minutes and there's no faxing! https://cla.azure.com.
    </p>

TTYL, AZPRBOT;

**Comment by paulbatum** [comment]
Just curious, what does this setting actually do? Can you explain the headache?

**Comment by ggailey777** [comment]
It sets the debugging to Xamarin for the project:
xamarin-debug
Without this it defaults to Windows debugging which never works because it doesn't attach to the device/emulator.

**Comment by paulbatum** [comment]
So basically if you open the project in VS, its more likely to work from an F5 with this change?

**Comment by ggailey777** [comment]
Yes, more like 80% 😉
Or to be more correct, it's more likely to attach the debugger to the emulator process.

**Pull request merged**
