### PR TITLE
Update TodoItemManager.cs

### PR DESCRIPTION
**Pull request by wesmc7777**
Need to expose the MobileServiceClient for access from the client projects. The client projects for Xamarin.Forms need to execute client specific methods off the MobileServiceClient for push notifications and authentication.

### CODE REVIEW

**Comment by azurecla** [comment]
Hi **@wesmc7777**, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <p>
        It looks like you're working at Microsoft (wesmc). If you're full-time, we DON'T require a contribution license agreement.
    </p>
    <p>
        If you are a vendor, DO please sign the electronic contribution license agreement. It will take 2 minutes and there's no faxing! https://cla.azure.com.
    </p>

TTYL, AZPRBOT;

**Comment by wesmc7777** [comment]
Hoping someone has time to review this.  This has impact on the Mobile Apps documentation.

**Comment by wesmc7777** [comment]
I'm not sure I follow.  I think its much different scenario with the iOS project you show here.  Because QSTodoService can be iOS specific and could simply implement the iOS specific approaches to getting the Push object and calling the LoginAsync method. So no need to expose the MobileServiceClient. It can stay private as it is there now.

In this PR I'm proposing we allow access to the client of the Xamarin portable class library. It needs to be exposed so customers can execute client specific LoginAsync() for iOS, Android, and Windows.   Also customers need the Push object from the client which differs for iOS (APNS), Android (GCM), and Windows (WNS/MPNS).  Does this make sense?

**Comment by phvannor** [comment]
Gavin was referring to the pattern on making the QSTodoService Static and creation of the service, not the exposing of the client object off of the static QSTodoService (which is fine as is)

**Comment by wesmc7777** [comment]
Yes, sorry I see your point now.  See if you agree with these updates

**Pull request merged**
